### ISSUE TITLE
Fix path for assets (images, fonts, etc.) folder

### ISSUE THREAD

**Issue by paulomfr** [Apiki/wpsteak-plugin#341]
## Version

  - WP Steak Plugin: 3.0.1
  - WordPress: 5.4
  - PHP: 7.4.2

## Expected behavior
Be able to import images and fonts from resources folder.

## Actual behavior
The Webpack configuration is not finding my images files from images folder, this appear that is a missing configuration in `file-loader`.

## Comments
```js
{
        test: utils.tests.images,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: file => `images/[name].${utils.filehash(file).substr(0, 10)}.[ext]`,
              publicPath: `/app/plugins/plugin-name/dist/`
            },
          },
        ],
      },
```
By adding a `publicPath` you can solve this.

**Comment by elvishp2006** [comment]
Hey @paulomfr thankyou for your contribution.

The `publicPath` should be a generic thing, we can't lock the ppl to use WordPress Bedrock structure.
